{% set name = "cryohub" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cryohub-{{ version }}.tar.gz
  sha256: 49c411f17aff96cbdec6b5a748112d5a232ea7381d3b7d2892f83bb998b33259

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - click
    - cryotypes >=0.2.0
    - dask-core
    - dynamotable >=0.2.4
    - emfile >=0.3
    - h5py
    - ipython
    - mrcfile >=1.3.0
    - numpy
    - pandas
    # - pydantic  # Declared but not imported in source
    - python >=3.8
    - scipy
    - starfile >=0.4.5

test:
  imports:
    - cryohub
  commands:
    - pip list
    # - pip check  # Fails due to pydantic
  requires:
    - pip

about:
  home: https://pypi.org/project/cryohub
  summary: IO hub for Cryo-EM, Cryo-ET and subtomogram averaging data.
  license: GPL-3.0-only
  license_file: LICENSE
  dev_url: https://github.com/teamtomo/cryohub

extra:
  recipe-maintainers:
    - alisterburt
    - brisvag
    - goanpeca
