{% set name = "cryohub" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cryohub-{{ version }}.tar.gz
  sha256: ce0c641e02613d08c49740a56905cc994ce2d3c1f4f996a1666a4ffd92058fe6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - click
    - cryotypes
    - dask-core
    - dynamotable >=0.2.4
    - emfile >=0.3
    - ipython
    - mrcfile >=1.3.0
    - numpy
    - pandas
    - pydantic
    - python >=3.8
    - scipy
    - starfile >=0.4.5

test:
  imports:
    - cryohub
  commands:
    - pip list
    # - pip check  # Uncomment when new release relaxes dependencies
  requires:
    - pip

about:
  home: https://github.com/teamtomo/cryohub
  summary: IO hub for Cryo-EM, Cryo-ET and subtomogram averaging data.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alisterburt
    - brisvag
    - goanpeca
