{% set name = "cryohub" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cryohub-{{ version }}.tar.gz
  sha256: f3630fee37b493e55948b35d017d5a9d10ca80d198e63cf6688df285c058a358

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - click
    - cryotypes >=0.2.0
    - dask-core
    - dynamotable >=0.2.4
    - emfile >=0.3
    - h5py
    - imagecodecs
    - ipython
    - mrcfile >=1.3.0
    - numpy
    - pandas
    - pydantic
    - python >=3.8
    - scipy
    - starfile >=0.5
    - tifffile
    - zarr

test:
  imports:
    - cryohub
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cryohub
  summary: IO hub for Cryo-EM, Cryo-ET and subtomogram averaging data.
  license: GPL-3.0-only
  license_file: LICENSE
  dev_url: https://github.com/teamtomo/cryohub

extra:
  recipe-maintainers:
    - alisterburt
    - brisvag
    - goanpeca
